// @5. Write a program to calculate Simple Interest using the formula:
//         (SI = P * R * T / 100).
//        Where:
// P = Principal amount
// R = Rate of interest (in %)
// T = Time (in years)

let principalAmount = 45050; //Amount
let rateOfInterest = 12; // %
let time = 2 ; //year

let SI = (principalAmount * rateOfInterest * time )/ 100;
console.log(`Calculated simple interest is - ${SI}`);

